name: textlab
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26
  - scipy=1.13
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyterlab
  - gensim
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8  
  - transformers
  - tqdm
  - tensorboard
  - pip
  - pip:
      - sentencepiece 